default: &defaults
  instagram:
    client_id: <%= ENV['INSTAGRAM_CLIENT_ID'] %>
    client_secret: <%= ENV['INSTAGRAM_SECRET'] %>
    access_token: <%= ENV['INSTAGRAM_TOKEN'] %>
  indextank:
    api_url: <%= ENV['INDEXTANK_API_URL'] %>
  mongodb:
    url: <%= ENV['MONGOHQ_URL'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
